from pathlib import Path

path = Path("app/services/vps.py")
text = path.read_text(encoding="utf-8")
old_block = "        self.db.add_all([session, user, worker])\n        self.db.commit()\n        self.db.refresh(session)\n\n        if self.event_bus:\\n            if self.event_bus:\\n                await self.event_bus.publish(session.id, {\n            \"event\": \"checklist.update\",\n            \"data\": {\"items\": session.checklist},\n        })\n        if self.event_bus:\\n            if self.event_bus:\\n                if self.event_bus:\\n            await self.event_bus.publish(session.id, {\n                \"event\": \"status.update\",\n                \"data\": {\"status\": session.status},\n            })\n\n        try:\n            secret = decrypt_secret(worker_token.token_ciphertext)\n            await dispatcher.dispatch_job(\n"
if old_block not in text:
    raise SystemExit("old block not found")
new_block = "        self.db.add_all([session, user, worker])\n        self.db.commit()\n        self.db.refresh(session)\n\n        if self.event_bus:\n            await self.event_bus.publish(session.id, {\n                \"event\": \"checklist.update\",\n                \"data\": {\"items\": session.checklist},\n            })\n            await self.event_bus.publish(session.id, {\n                \"event\": \"status.update\",\n                \"data\": {\"status\": session.status},\n            })\n\n        try:\n            secret = decrypt_secret(worker_token.token_ciphertext)\n            await dispatcher.dispatch_job(\n"
text = text.replace(old_block, new_block)

old_fail = "            self.db.add_all([session, user, worker])\n            self.db.commit()\n            if self.event_bus:\\n            if self.event_bus:\\n                if self.event_bus:\\n                await self.event_bus.publish(session.id, {\n                    \"event\": \"status.update\",\n                    \"data\": {\"status\": \"failed\", \"message\": \"Kh�ng th? giao vi?c cho worker\"},\n                })\n            raise HTTPException(status_code=status.HTTP_502_BAD_GATEWAY, detail=\"Worker kh�ng ph?n h?i\") from exc\n\n        session.status = \"provisioning\"\n        session.updated_at = datetime.now(timezone.utc)\n        self.db.add(session)\n        self.db.commit()\n        if self.event_bus:\\n            if self.event_bus:\\n                if self.event_bus:\\n            await self.event_bus.publish(session.id, {\n                \"event\": \"status.update\",\n                \"data\": {\"status\": \"provisioning\"},\n            })\n        return session\n"
new_fail = "            self.db.add_all([session, user, worker])\n            self.db.commit()\n            if self.event_bus:\n                await self.event_bus.publish(session.id, {\n                    \"event\": \"status.update\",\n                    \"data\": {\"status\": \"failed\", \"message\": \"Không thể giao việc cho worker\"},\n                })\n            raise HTTPException(status_code=status.HTTP_502_BAD_GATEWAY, detail=\"Worker không phản hồi\") from exc\n\n        session.status = \"provisioning\"\n        session.updated_at = datetime.now(timezone.utc)\n        self.db.add(session)\n        self.db.commit()\n        if self.event_bus:\n            await self.event_bus.publish(session.id, {\n                \"event\": \"status.update\",\n                \"data\": {\"status\": \"provisioning\"},\n            })\n        return session\n"
text = text.replace(old_fail, new_fail)

path.write_text(text, encoding="utf-8")
